services:
  - type: web
    name: jobsyncpro
    env: python
    pythonVersion: 3.11   # ✅ correct field name
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        fromSecretFile: /etc/secrets/gemini_api_key
      - key: FIREBASE_SERVICE_ACCOUNT
        fromSecretFile: /etc/secrets/firebase_service_account
